# Importar el .env de forma opcional
spring.config.import=optional:file:.env[.properties]

# Puerto
server.port=8081

# Base de datos PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate  
#spring.jpa.hibernate.ddl-auto=validate/update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# llave secreta para JWT
jwt.secret=${TOKEN_JWT_SECRET}
admin.initializer.password=${ADMIN_PASSWORD}

# conf para mostrar mensajes de error en la respuesta
server.error.include-message=never

# Configuración de CORS
cors.allowed-origin=${FRONTEND_URL}
