# Puerto
server.port=8080

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica_db
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_PASSWORD

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# llave secreta para JWT
jwt.secret=TU_LLAVE_MIN_32_CARACTERES

admin.initializer.password=TU_PASSWORD_ADMIN